#pragma once
#include <iostream>
#include <string>
#include <assert.h>
#include <crtdbg.h>
#include <stdexcept>
#include <sstream>
#include <fstream>
#include <memory>
#include <vector>
#include <algorithm>
#include <random>
#include <map>
#include <set>
#include <unordered_map>

#include <QtWidgets/QMainWindow>
#include <QtWidgets/qboxlayout.h>
#include <QtWidgets/qpushbutton.h>
#include <QtWidgets/QApplication>
#include <QtWidgets/qlabel.h>
#include <QtWidgets/qspinbox.h>
#include <QtWidgets/qslider.h>
#include <QtWidgets/qlineedit.h>
#include <QtWidgets/qlistwidget.h>
#include <QtWidgets/qboxlayout.h>
#include <QtWidgets/qformlayout.h>
#include <QtWidgets/qlistview.h>
#include <QMessageBox>
#include <QComboBox>
#include <qcheckbox.h>
#include <QtWidgets/qframe.h>
#include <QtWidgets/qtablewidget.h>
#include <qlayout.h>
#include <qrandom.h>
#include <QGraphicsView>
#include <QGraphicsPixmapItem>
#include <qgraphicsscene.h>
#include <qdebug.h>
#include <QFileDialog>
#include <qpalette.h>

#include "Domain.h"
#include "Tests.h"
#include "Exceptions.h"
#include "Validate.h"
#include "Repository.h"
#include "UndoAction.h"
#include "ShoppingCart.h"
#include "Service.h"
#include "UI.h"
#include "GUI.h"
#include <assert.h>
#include <stdlib.h>
#include <crtdbg.h>
#define _CRTDBG_MAP_ALLOC